# Generated by Django 4.2.6 on 2023-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daneshgah', '0002_edcert_file_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(default='-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='-1', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniquenum',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
