# Generated by Django 4.2.6 on 2023-10-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daneshgah", "0004_it_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="it",
            name="test",
        ),
    ]
