# Generated by Django 4.2.6 on 2023-10-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daneshgah", "0005_remove_it_test"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="it",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
    ]
