# Generated by Django 4.2.5 on 2023-11-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daneshgah", "0007_alter_deputyofeducation_options_alter_it_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencydrop",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="termdrop",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="abstractcourse",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="daneshgah.abstractcourse"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="degree",
            field=models.CharField(max_length=20),
        ),
    ]
